server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
  connection-timeout: 5000ms
  servlet:
    context-path: /lana-boot

# swagger配置
knife4j:
  # 开启增强模式
  enable: false
  # 开启生产环境保护
  production: false
  # 开启认证功能
  basic:
    enable: false
    username: admin
    password: 123456
# minio配置
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: Sdls1234@#
  bucketName: data
  httppoint: http://127.0.0.1:9000

spring:
  # 环境 dev|uat|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 127.0.0.1
    port: 5419
    password: Sdls@#$2021 # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  resources:
#    add-mappings: false


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描
  typeAliasesPackage: com.lana.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

